export const GET_INS_ACCOUNTS = "GET_INS_ACCOUNTS";
export const ADD_INS_ACCOUNT = "ADD_INS_ACCOUNT";
export const DELETE_INS_ACCOUNT = "DELETE_INS_ACCOUNT";
export const UPDATE_INS_ACCOUNT = "UPDATE_INS_ACCOUNT";
export const SELECT_INS_ACCOUNT = "SELECT_INS_ACCOUNT";

export const GET_SETTINGS = "GET_SETTINGS";

export const GET_INS_TAGS = "GET_INS_TAGS";
