# Generated by Django 2.2.1 on 2019-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(1, 'VALID'), (2, 'WARNED'), (3, 'BANNED')], null=True),
        ),
    ]
