# Generated by Django 2.2.1 on 2019-05-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0002_auto_20190506_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=30)),
                ('port', models.CharField(max_length=10)),
            ],
        ),
    ]
