# Generated by Django 2.2.1 on 2019-05-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0003_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LastName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working', models.BooleanField(default=False)),
                ('times_per_proxy', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='proxy',
            name='used_for_register',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
